# site settings
title: rmzamora.github.io
subtitle: Tech How To
email: mellzamora@outlook.com
description: A life of a tech geek.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: My Street
city: Our City
state: PH
zip_code: 88888
country: Philippines
phone: (xxx) XXX-XXXX

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
